version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            docker build -t rishabh336/todo:latest .
            docker push rishabh336/todo:latest
